[[pocl]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "46d10ee2d8c30f9f1e1f4c8c5eb7b7fb981cfa31"
libc = "glibc"
os = "linux"

    [[pocl.download]]
    sha256 = "f888b02992155677566ac4579cd7d6724453d7bc39fce4c34e52f51ec0c457fc"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.1.2+2/pocl.v7.1.2.i686-linux-gnu-cxx11.tar.gz"
[[pocl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e3b7a809064c4fe482197a90d9078f4e60418784"
libc = "glibc"
os = "linux"

    [[pocl.download]]
    sha256 = "0a5a6d5dba6f9bbc505fd36409f9fc5a43225de30de6aef55e9a47573646774c"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.1.2+2/pocl.v7.1.2.x86_64-linux-gnu-cxx11.tar.gz"
[[pocl]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "13212de1b063c4a3dd1e1d4edc2dfb74e06c154b"
libc = "glibc"
os = "linux"

    [[pocl.download]]
    sha256 = "67b5e8e531cc04916ff99f2ed3cb73cb46caaf04de90487b91faa525ad2ffca5"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.1.2+2/pocl.v7.1.2.aarch64-linux-gnu-cxx11.tar.gz"
[[pocl]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "95392384ddd98cb5b22dd66ebd1a65e007aefdea"
libc = "glibc"
os = "linux"

    [[pocl.download]]
    sha256 = "f9e12b642c2024f1ad9e37bf1e4d990db84f4115430ff542cdf6dcd63e008995"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.1.2+2/pocl.v7.1.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[pocl]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b12c710c04d894bd40ebf62de622aed1a8e3ac45"
libc = "glibc"
os = "linux"

    [[pocl.download]]
    sha256 = "a51de084f8d3f258daa4f63527b029dbbbffcf555f80b4cdeb86477062a1094b"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.1.2+2/pocl.v7.1.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[pocl]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0c8f571bc1768fbc9303fadcb7095ba5a17dcb39"
libc = "glibc"
os = "linux"

    [[pocl.download]]
    sha256 = "d395561316001d13a906ac68c2dba168303892bf98e12f1d670231f34eead570"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.1.2+2/pocl.v7.1.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[pocl]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a83f667215cdf29e42d6bbe46ad8344f06306537"
libc = "glibc"
os = "linux"

    [[pocl.download]]
    sha256 = "2db51a9b8c1ea8f7f0106b10e962043574c7e2fa2e78ef7fc78f5e86f6b45608"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.1.2+2/pocl.v7.1.2.riscv64-linux-gnu-cxx11.tar.gz"
[[pocl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0bb699c05d80aade0c8bed2ddc545144fe4d001d"
libc = "musl"
os = "linux"

    [[pocl.download]]
    sha256 = "b88ab84507b98b55211e3a8c9f0cb2ee98011753f7c08ddf983e8739a1d63846"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.1.2+2/pocl.v7.1.2.x86_64-linux-musl-cxx11.tar.gz"
[[pocl]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "393a77cd738ebd54b38de130f2cadc00bb71404e"
libc = "musl"
os = "linux"

    [[pocl.download]]
    sha256 = "81c750af13edbc59a5c4cb8bdab3d2ecdd1fb0f8cb1a1fe6ff7934e72d2bfa7a"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.1.2+2/pocl.v7.1.2.aarch64-linux-musl-cxx11.tar.gz"
[[pocl]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e24aaa951a727d94e2a977d889d2de184c69a3cf"
libc = "musl"
os = "linux"

    [[pocl.download]]
    sha256 = "04ab8482a610cdd11ee562d08bab845ec0a76ab84b5a1d9c2112f3720b98d805"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.1.2+2/pocl.v7.1.2.armv6l-linux-musleabihf-cxx11.tar.gz"
[[pocl]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c1079d72e68b9777d0f8fa2f8185a200a936b223"
libc = "musl"
os = "linux"

    [[pocl.download]]
    sha256 = "36b6ae69594f248a5c807fc3e0192293a9a08d58e328c428c2cc07d6377c782b"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.1.2+2/pocl.v7.1.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[pocl]]
arch = "x86_64"
git-tree-sha1 = "675fe3749608575ab477b741d8e41a2680d3688c"
os = "macos"

    [[pocl.download]]
    sha256 = "310738aa30c87071e715a1a7c3bd8fbbcf9be104d32a5ae49c9689b10cbcf9ca"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.1.2+2/pocl.v7.1.2.x86_64-apple-darwin.tar.gz"
[[pocl]]
arch = "aarch64"
git-tree-sha1 = "deb3ff1c1b6bd0a71bb5ee1548fc5c87be5b33bb"
os = "macos"

    [[pocl.download]]
    sha256 = "7c352173a41367ab5931608128eae2463e8d0dceee0647a253261c0057b5ba6f"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.1.2+2/pocl.v7.1.2.aarch64-apple-darwin.tar.gz"
[[pocl]]
arch = "x86_64"
git-tree-sha1 = "2ff220c073ea7f0638d1254715bc3bc5a3295473"
os = "freebsd"

    [[pocl.download]]
    sha256 = "1e5c0c599a55e2ee03509a652631275bb68668841c6823373a8af2396d83b616"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.1.2+2/pocl.v7.1.2.x86_64-unknown-freebsd.tar.gz"
[[pocl]]
arch = "aarch64"
git-tree-sha1 = "b3de700623eb83c55d67d59041da46764bf8f6ef"
os = "freebsd"

    [[pocl.download]]
    sha256 = "fb59d4b9ecbfef34d67c70863e890d29d305b3415bae7b5d833a6e8ef4474e13"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.1.2+2/pocl.v7.1.2.aarch64-unknown-freebsd.tar.gz"
[[pocl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3c23796f16f20ffae5915b43e2850c9ab1aff987"
os = "windows"

    [[pocl.download]]
    sha256 = "9a9bff0cb1b831f5b3968f0e9c4ee51bb0c5c69f7ed954483ea08efbd49ca69a"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.1.2+2/pocl.v7.1.2.x86_64-w64-mingw32-cxx11.tar.gz"
