[[pocl]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5826f236bde1f39716056482e2b79d2b12d393ee"
libc = "glibc"
os = "linux"

    [[pocl.download]]
    sha256 = "4e2f527942afd720b040692380e6137560466035b5496258c7110ab270d22436"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+9/pocl.v7.0.0.i686-linux-gnu-cxx03.tar.gz"
[[pocl]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "57ef2f92c101d7993db851411a650318713492a1"
libc = "glibc"
os = "linux"

    [[pocl.download]]
    sha256 = "f41b12f5edf3aee64c5c31e4a82c03602ccff7837dc93a8c5e8ad4deb7bccc3f"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+9/pocl.v7.0.0.i686-linux-gnu-cxx11.tar.gz"
[[pocl]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f6e4c0d64233579e85bdc5f598d89a6be9274879"
libc = "glibc"
os = "linux"

    [[pocl.download]]
    sha256 = "d4b9ba2a8e1d30116d0c5808c42fbfda160495d5e28721524c76e012932070cc"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+9/pocl.v7.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[pocl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "057a88cf7204e381a73176dbe3fc5e32b693ff00"
libc = "glibc"
os = "linux"

    [[pocl.download]]
    sha256 = "86b0119361dfd02d80fc2435dc23044fef7e74547a5d7014f3c80157b6aaf567"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+9/pocl.v7.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[pocl]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b84c19f0c4a39cd1cb3489e8d36a6c35994f909c"
libc = "glibc"
os = "linux"

    [[pocl.download]]
    sha256 = "19aa4918f009e46817ba780df6bfed37700fb0c615fcb8fe4c36434bf0e91001"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+9/pocl.v7.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[pocl]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cb6550f748920bb7becef2d8bc901375664de732"
libc = "glibc"
os = "linux"

    [[pocl.download]]
    sha256 = "a064548ed90d06bfa79efe392eea369a1be7fdb022d0e210530e985bca866d9e"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+9/pocl.v7.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[pocl]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d6f39fcf1a84efb91837047ddf938b45158aa0c4"
libc = "glibc"
os = "linux"

    [[pocl.download]]
    sha256 = "a1051d6636cf070249179200faabdf21996d94f1560c6200366b4951e1c7b1ed"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+9/pocl.v7.0.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[pocl]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ed3acab79cb009dbdb72826d77c2506c46c275df"
libc = "glibc"
os = "linux"

    [[pocl.download]]
    sha256 = "2d5d13372cec07b6d5ac2377539aad72e7608845dbc8f22f56a66c665e94a8ee"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+9/pocl.v7.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[pocl]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0b0eb9e358abb1484e6185814cfd2b34c97453fb"
libc = "glibc"
os = "linux"

    [[pocl.download]]
    sha256 = "b5350c42e8c2096905c121d0a5c08482579d43ed9819fa8bcb104093a2ca1227"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+9/pocl.v7.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[pocl]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4a07aa55dc0ef46c1d811dbda9b061b67d87eaf2"
libc = "glibc"
os = "linux"

    [[pocl.download]]
    sha256 = "d975f71da5f1fdb805d722d36df35809d1c9b60f646349837f4f5e26d51def4f"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+9/pocl.v7.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[pocl]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b668648d3f48e4393d4d26e545fa64dfe8e41549"
libc = "glibc"
os = "linux"

    [[pocl.download]]
    sha256 = "53a3034d0d10fe013755abe314305264f8f57f716257e4f41a2a6f72e71ce9f3"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+9/pocl.v7.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[pocl]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ccaf3bdd1eba89c0aa4e3f1a19061d131ee8f178"
libc = "glibc"
os = "linux"

    [[pocl.download]]
    sha256 = "d5ef15b98eef396464ad5f79d39541beb68319badf3a67b5791dbdee92e6997b"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+9/pocl.v7.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[pocl]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ef3d00a3ca0fc94a197a7f00e0b9ef7452290503"
libc = "glibc"
os = "linux"

    [[pocl.download]]
    sha256 = "41e84765025ef5ef39617e8115c681f36d03a3352b03069b73e4b6825821aa62"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+9/pocl.v7.0.0.riscv64-linux-gnu-cxx03.tar.gz"
[[pocl]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e37e6e5cf2890f9674f3d506bb642119ae79ead9"
libc = "glibc"
os = "linux"

    [[pocl.download]]
    sha256 = "4c90559d379b2b8629a83e34e6f41f8ee3f896352a7d83ec4263a5a94c7ba57c"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+9/pocl.v7.0.0.riscv64-linux-gnu-cxx11.tar.gz"
[[pocl]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e0f0688af01bf9919f746ed6e20f5a33af598daa"
libc = "musl"
os = "linux"

    [[pocl.download]]
    sha256 = "dbef1d9ec404f7189e223ed83a530d831a41caf749ed07cbcb02bd19b17468e5"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+9/pocl.v7.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[pocl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c858adf01e6f74b6c08c19caae2888d0cf3f7f10"
libc = "musl"
os = "linux"

    [[pocl.download]]
    sha256 = "582e70f8de7a605640d259dd482bca835121f820bb1b4c17171bcbb3c3de71cd"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+9/pocl.v7.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[pocl]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cd4d0a61a8fa448307d7b0eb406eaa035cc530d7"
libc = "musl"
os = "linux"

    [[pocl.download]]
    sha256 = "e42226ca7e8293a0b3609b465726cc08ba81f5dae1b904e861e447f3cfa1746a"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+9/pocl.v7.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[pocl]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ed43ececb92b057cc11b9c867e3818cb8ab66939"
libc = "musl"
os = "linux"

    [[pocl.download]]
    sha256 = "fa8f904d6c7fd78a7d303d1b6337b515f30be85039e5c48b32ef05d29e00a42a"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+9/pocl.v7.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[pocl]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3ef5999f7d9922bac31323a360c023b54059308d"
libc = "musl"
os = "linux"

    [[pocl.download]]
    sha256 = "5bf8c03e9dfc684efe1d219baa3956bbfb960c8c62cece687f15f7f0a981245e"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+9/pocl.v7.0.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[pocl]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "37274edbef74edec76a626ac9cba589910ce7c7f"
libc = "musl"
os = "linux"

    [[pocl.download]]
    sha256 = "e732661687ef7fded1e27bb4c43a4d37f6e8c81606f871642769ef39d987f6dd"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+9/pocl.v7.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[pocl]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a72db43d61901eaab14acaebcc06449b39125790"
libc = "musl"
os = "linux"

    [[pocl.download]]
    sha256 = "78d65d095dfe924236fcfb68746dad76b70520ad421eb65b962a87bf9abed442"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+9/pocl.v7.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[pocl]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6acd43800444e96e6e7a0846643a8488e0899deb"
libc = "musl"
os = "linux"

    [[pocl.download]]
    sha256 = "aa3907e170380cd8e29d0aed0c40fea5b85a91124c60182e10be9cae5c6d89a2"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+9/pocl.v7.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[pocl]]
arch = "x86_64"
git-tree-sha1 = "3667256e71f49ae03bfd900365c9375f1091e4cf"
os = "macos"

    [[pocl.download]]
    sha256 = "c2bc7bfa54388e5882da29bb444ff819f31c27ee79d70dd17231db875be93b3e"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+9/pocl.v7.0.0.x86_64-apple-darwin.tar.gz"
[[pocl]]
arch = "aarch64"
git-tree-sha1 = "baa385b3cc0fc1621391ad627270830db6accfae"
os = "macos"

    [[pocl.download]]
    sha256 = "2c4ddfbffbc5bdc5a6d3d6aa312df8b40bed546233fc8a8421ed59ed35eeb5ae"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+9/pocl.v7.0.0.aarch64-apple-darwin.tar.gz"
[[pocl]]
arch = "x86_64"
git-tree-sha1 = "f3fdfbbebe91f57c30a9fa433ca1da3e013afd7f"
os = "freebsd"

    [[pocl.download]]
    sha256 = "1ccb47c61eec5a4ae5ee124fcb85846b55d0ba5e5712ce4d73c6f524d99e7c69"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+9/pocl.v7.0.0.x86_64-unknown-freebsd.tar.gz"
[[pocl]]
arch = "aarch64"
git-tree-sha1 = "a99d2f100cdaef6a851f64bcec398bd2ba85a1c7"
os = "freebsd"

    [[pocl.download]]
    sha256 = "e6289c24f3819301ed746c8210d5b89ef3a98efd52c4409f9486f93b4e68a49c"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+9/pocl.v7.0.0.aarch64-unknown-freebsd.tar.gz"
[[pocl]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "80c650fcd04848e04b790b11f0d8f892772119a3"
os = "windows"

    [[pocl.download]]
    sha256 = "e4a82e03a8cd375941d6626c2ff9e394d2ebe2f95ce42dbdab333ea91203a270"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+9/pocl.v7.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[pocl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eb52dfcc778ca541a5724371cf99f6a2351044f5"
os = "windows"

    [[pocl.download]]
    sha256 = "87ea0679f82764d4aac2b5690fbfcb6665267aaf1a2bb0f51e4105c386623ac8"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+9/pocl.v7.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
