[[pocl]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9c9d46cd76cb3e5c97b30ce684e931470e382c4a"
libc = "glibc"
os = "linux"

    [[pocl.download]]
    sha256 = "ce4b51400b95e849b6c10f3f2b8320e455a7d4c493c47d225970719019c8e4e7"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+3/pocl.v7.0.0.i686-linux-gnu-cxx03.tar.gz"
[[pocl]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c02df9dea9e3ddbd47e6f0dbed12e4c52533e93d"
libc = "glibc"
os = "linux"

    [[pocl.download]]
    sha256 = "ed0f9a778ff2f8d99a0f05d27007cd5fbbb63671820a41efe8097401c1574ab6"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+3/pocl.v7.0.0.i686-linux-gnu-cxx11.tar.gz"
[[pocl]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a5d2b3ab263f2a09a380eff77ba73d86e1207a33"
libc = "glibc"
os = "linux"

    [[pocl.download]]
    sha256 = "e72950d6712995ecee63bbd43694252e7f274680d516c53437702619b17de4e9"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+3/pocl.v7.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[pocl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a2c674d68529995b77b90fe2e72607f0bb0cc94"
libc = "glibc"
os = "linux"

    [[pocl.download]]
    sha256 = "38afc46a1c848c884eb3391481e63f2bca285c81d9a8c41070514239946be79b"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+3/pocl.v7.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[pocl]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f0d40fe99646ce794f0d71e0128aad113701a53a"
libc = "glibc"
os = "linux"

    [[pocl.download]]
    sha256 = "797c13f396112f45a553bb155c18fc43085ea3e1717b9df08bac381f7c2a9f1b"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+3/pocl.v7.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[pocl]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "baf5f767d2ab4f4913cd6ef412489dd0b3794501"
libc = "glibc"
os = "linux"

    [[pocl.download]]
    sha256 = "80c864e9e3650f7d2a4b4c92eeb4818cec4e3a2a93c221c284f05e35ddf1ec56"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+3/pocl.v7.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[pocl]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "17cc44919090c93c13b25d467f332c3b2dd168b6"
libc = "glibc"
os = "linux"

    [[pocl.download]]
    sha256 = "bd83344dc2fff368df7244a4a49ee9e32129e119df61f3b580f72a7071464899"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+3/pocl.v7.0.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[pocl]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "13593691fafa92e516bd8eb130cbc4e4d12f3b95"
libc = "glibc"
os = "linux"

    [[pocl.download]]
    sha256 = "a0bfe9fe67e9a43c402a6a1b28b3f9e2418d0c6ea0475c424e5495f1cbffa271"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+3/pocl.v7.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[pocl]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4f6c6456aae93cc27f8a78e3d749724423e293d1"
libc = "glibc"
os = "linux"

    [[pocl.download]]
    sha256 = "b1372b9fe38acebeda9571eb8128c3c776a498a89e883a4460bbf5a538bfcd5d"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+3/pocl.v7.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[pocl]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3e13ec6c152704245cbe997606b8529857fc4b3f"
libc = "glibc"
os = "linux"

    [[pocl.download]]
    sha256 = "17b56585a918fd1f40582fad7e406f01a313d451bb2a2547bbfd68e9ad2fc4d2"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+3/pocl.v7.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[pocl]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d7d97bc74388b0da4dae4bdcb33121af30437ee5"
libc = "glibc"
os = "linux"

    [[pocl.download]]
    sha256 = "3ff55f7dbf76477bc45fec66b2f9d65cf03c69fc062c8f6d66af439e1cf2e088"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+3/pocl.v7.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[pocl]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3b337f906ac7da500e9de472d85e8672ddcec7f8"
libc = "glibc"
os = "linux"

    [[pocl.download]]
    sha256 = "a0b04f451e7d296d5658a197c37e922ec085f76f804c769533aaa23039a37694"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+3/pocl.v7.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[pocl]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "83812898132f885c4d76a6acbe3489c00d993bec"
libc = "glibc"
os = "linux"

    [[pocl.download]]
    sha256 = "381ccb08c02a11f0cb4bb4601aa3b1b37a01b6ded014b75308c7f1618ecae3bb"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+3/pocl.v7.0.0.riscv64-linux-gnu-cxx03.tar.gz"
[[pocl]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "201e8f777c77c418cd3c637f50e047cbaba908a3"
libc = "glibc"
os = "linux"

    [[pocl.download]]
    sha256 = "a8064a5380cd3dfabd3b1d0ea56d682d26f4c8b99fad75668ad7c866171c6d7c"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+3/pocl.v7.0.0.riscv64-linux-gnu-cxx11.tar.gz"
[[pocl]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bc06cc8c1fbe302b985d8cfa66124df595c8ecbd"
libc = "musl"
os = "linux"

    [[pocl.download]]
    sha256 = "303216229e912272a8b10391c7bf40b9ba5b2019eb5f4ff9b8c0d6caac58e12f"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+3/pocl.v7.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[pocl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9fea30e39ec5527542e7ebe8a4949457c5775042"
libc = "musl"
os = "linux"

    [[pocl.download]]
    sha256 = "b9f245c5caa0298e747a33c1941849d5d798f79ed66f9784964e12d154174a4d"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+3/pocl.v7.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[pocl]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4314d109039f62a575bb58c8176820700f00782d"
libc = "musl"
os = "linux"

    [[pocl.download]]
    sha256 = "5e0268eaba10d890d89c323cab789bbcb3092f08fd5aa5cd548ffa09bfa5b367"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+3/pocl.v7.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[pocl]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fbcfafded81d1b3c44bb8963a8e761a6e873de35"
libc = "musl"
os = "linux"

    [[pocl.download]]
    sha256 = "d403ebbcf235dca2d718ac2d269440835853764ec6919aa40f01f742048cfbf7"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+3/pocl.v7.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[pocl]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7a1f588f530fdd550bfa11883f1a0e9a7e600a66"
libc = "musl"
os = "linux"

    [[pocl.download]]
    sha256 = "b5f9c77a5e62b878ea6f81e8dc835fb1054cc2fb04ecbb9700476c8535b21fcc"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+3/pocl.v7.0.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[pocl]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "da3f0dd76b7186d0382e5d2bd46cd51754ee65de"
libc = "musl"
os = "linux"

    [[pocl.download]]
    sha256 = "ef91b679f85a7122ccadaf7a26d777ec734c781c1613cec22888587223a63a21"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+3/pocl.v7.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[pocl]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "da79edc384348abdaabdf71f6be79183c8d2a177"
libc = "musl"
os = "linux"

    [[pocl.download]]
    sha256 = "21d2e7bf4760c30afcd41301f03668e986c42e835e91820c170466112439c467"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+3/pocl.v7.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[pocl]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6d2f89f7ba390c686c27f9406e796ca8313ab35e"
libc = "musl"
os = "linux"

    [[pocl.download]]
    sha256 = "188ba39f147ddd7c742a4e76ac736f893f05a0b17e2dc93cf1aa8d614779bb21"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+3/pocl.v7.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[pocl]]
arch = "x86_64"
git-tree-sha1 = "290abe3c73127605504eb5d721d79c5b8ed1c461"
os = "macos"

    [[pocl.download]]
    sha256 = "eddc9795bdf14b4754c049174f084ab5512e69535be70e441e23f626c3f50ff7"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+3/pocl.v7.0.0.x86_64-apple-darwin.tar.gz"
[[pocl]]
arch = "aarch64"
git-tree-sha1 = "daf8c6d65d09ff2a3c3640eb1f41f0f205e1e93c"
os = "macos"

    [[pocl.download]]
    sha256 = "1c0e5e5aaa59ef8485290a7f1e58d097a4d92d3fa4cbdeb76ddc6decaf2133c0"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+3/pocl.v7.0.0.aarch64-apple-darwin.tar.gz"
[[pocl]]
arch = "x86_64"
git-tree-sha1 = "c961e62b55d6499da5d20cb66c7fc9aec7e1d9d3"
os = "freebsd"

    [[pocl.download]]
    sha256 = "fb5999fc46739987683c55f7658ca5a69eaf635937c995cc116918b90c626c87"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+3/pocl.v7.0.0.x86_64-unknown-freebsd.tar.gz"
[[pocl]]
arch = "aarch64"
git-tree-sha1 = "6bdb5932764bff2f6f9183b7f11cad9237493e07"
os = "freebsd"

    [[pocl.download]]
    sha256 = "da95deca8999baf0e98fcf681d52afb01eb8a468c885bbc44e646c7d3583e496"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+3/pocl.v7.0.0.aarch64-unknown-freebsd.tar.gz"
[[pocl]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "22d496847e84e28882491ededda0d918aa96c261"
os = "windows"

    [[pocl.download]]
    sha256 = "b7eb8381f3524c6c4215d23fadb78ea0623164a66ef62db66fbae0a15571425e"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+3/pocl.v7.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[pocl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "482e5885bb5283f1e2237b2edab3067384b2e31a"
os = "windows"

    [[pocl.download]]
    sha256 = "5fd579784b2ffbd11bf7a5746a0d225da210b1dc84ade840b864c0c88d24f1e1"
    url = "https://github.com/JuliaBinaryWrappers/pocl_jll.jl/releases/download/pocl-v7.0.0+3/pocl.v7.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
